### ISSUE TITLE
It's posible to compile that to run in iPhone?

### ISSUE THREAD

**Issue by matiasfha** [liuliu/ccv#1]
Well.. i'm running OpenCV in iphone but it's extremly low.. so i wondering if your project can run in iPhone..

**Comment by liuliu** [comment]
I've only managed to compile ccv on Mac OSX, for which you have to manually disable several compile options (fftw, cblas etc.). The code is portable (except Microsoft Visual C++) and it can be compiled against clang/gcc/icc. However, it is not optimized for iPhone yet and the architecture is mainly targeting at server-side use cases (for example, the cache ability). Embedded system is not a focus right now. For all, it is still an experimenting project, I don't recommend any serious production-ready usage.

**Comment by matiasfha** [comment]
(sorry for my english)
So it's possible compile in Mac OSX... i tried but i have a lot of compile errors..

Can you post the makefile to compile in Mac?..
I thing maybe it's posible to make fat-libs to test in iphone.. i can do that..

**Comment by liuliu** [comment]
The last time I tried it, I installed libjpeg/libpng with homebrew, and then modified the CFLAG field in makefile to be:
CFLAGS = -O3 -msse2 -Wall -D HAVE_LIBJPEG -D HAVE_LIBPNG
Since ccv is statically linked to your app, you should include -ljpeg and -lpng for your app as well. For now, on non-intel arch, the line 117-145 in ccv_basic.c should be deleted since it uses SSE2 instruction.
With these changes, the SIFT and BBF apps should still work; the broken functions would be ccv_gemm and ccv_filter which requires CBLAS and FFTW. BBF for training is broken too since it requires GNU Scientific Library. I should add two functions so that you can disable cache functionality once I get time.

**Comment by liuliu** [comment]
Oh, btw, I tried to compile ccv to iOS and it is easy enough. Once 0.1 version is out, I will claim official support for iOS.
