### ISSUE TITLE
face detection

### ISSUE THREAD

**Issue by james-zhangyk** [liuliu/ccv#107]
Acf feature based method of piotr dollar's  toolbox get excellent performance for face detection and pedestrian detection. I appreciate you can implement this in your ccv (replace icf feature).

**Comment by guardrex** [comment]
I'd like to "vote" for that, too. But please make it an add-on and not a replacement. I think icfdetect is pretty good for what it does.

**Comment by liuliu** [comment]
Can you provide more details on that? I am closely looking at scores on FDDB to determine which one to implement: http://vis-www.cs.umass.edu/fddb/results.html

**Comment by liuliu** [comment]
The plan currently I have for face detection is to implement this: https://sites.google.com/site/leeplus/publications/learningsurfcascadeforfastandaccurateobjectdetection and then have a SVM classifier to eliminate more false positives.

**Comment by ghost** [comment]
Have you considered HeadHunter or Joint Cascade from papers: http://markusmathias.bitbucket.org/2014_eccv_face_detection/ and http://home.ustc.edu.cn/~chendong/JointCascade/ECCV14_JointCascade.pdf ? I've tried DPM baseline that HeadHunter creators provides(converted to FFLD2 for faster detection, ~100ms for image) and it's really good when facial landmarks are quite visible but fails to e.g. DLIB detector when it comes to small faces (even with upscaling). You could try headhunter via doppia if you have nvidia gpu (probably there's way to try it without gpu but I didn't have time to play with it). 
Second paper describes the approach from your last post but provides in their words a better solution without using svm which speed things up. I am in the same position in my work, I have to implement better solution then OpenCV's VJ or DLIB SVM apporach but couldn't decided which one yet. I think I could provide some help in implementation if you make a decision.

**Comment by lbin** [comment]
@shottedsheriff  Hi, recently, I also tried  http://markusmathias.bitbucket.org/2014_eccv_face_detection/ but I think they gave the wrong model, because the app cannot find the model. So pls give me some suggestion? Thank you.

**Comment by ghost** [comment]
@lbin Which app: DPM or Doppia? If DPM, then I didn't use voc-releas5 for detection (I've used some of its scripts to convert model). Here is the library I've used: https://github.com/fanxu/ffld2 which is much faster than DPM 5 and provides convertmodel5 script that allows you to convert dpm_baseline.mat to ffld2 format (you have to copy some functions from voc-release5 to the folder of convertmodel5.m, errors will be your guide :D ). All operations worked with Octave but I think you have to install some additional packages like image, statistics or something, don't remember. To have some reasonable detections use threshold between 3-5 and non-maxima-suppresion around 0.3, depands on data. I am not sure if they submitted right model either since it's not THAT good (or maybe my case have too difficult data). 
@liuliu : feel free to remove this comment if that's considered as spam but I thought someone else than lbin would find it usefull

**Comment by liuliu** [comment]
Oh, I don't mind. This is pretty informative.

**Comment by lbin** [comment]
@shottedsheriff  Thank you very much.

**Comment by lbin** [comment]
@shottedsheriff  ffld2 is a good sdk. I tried and succeed. Now I also want to try Doppia(
https://bitbucket.org/rodrigob/doppia/src/718a2dce82e630213f39fdcf0ebd429af89a390e/data/trained_models/face_detection/?at=preparing_v2) Do you know how to use this model(headhunter.proto.bin)? I got some error like "Can't open this model", any suggestion?
Thanks a lot.

**Comment by ghost** [comment]
@lbin Unfortunately I do not since I've got many problems with it because I'm on machine without GPU and I have now different tasks to finish before I can dig on that. I'll have access to my personal computer next week and then I can update info. But if you'll succeed please give some insights as well.

**Comment by liuliu** [comment]
I put a frontal face detector implementation with SCD in current unstable. It is only for frontal faces, and I will improve that for the next release (this will in 0.7 release, and will be improved in the release after that).

**Comment by Duffycola** [comment]
Hey, could you train a face detector for non-frontal faces as well? Or could you share your thoughts on this? I'm trying to achieve this at the moment... I feel like there's a great variety of datasets and in doppia they use DPM as a baseline for face detection. Would be interesting to train a face DPM (frontal and various angles). Also I noticed that it's really annoying to work with all the dataset formats. It would be great if you had in your library a few dataset conversion scripts to be more flexible in choosing data. Just some thoughts...

**Comment by Duffycola** [comment]
@shottedsheriff Could you provide the converted dpm_baseline.mat in ffld2 format? (I don't have matlab :'( )

**Comment by liuliu** [comment]
I don't have enough time to train non-frontal. The grand idea I have is to train a mixed SCD / ICF detector reaches state-of-the-art for face detection. Then we will tune the parameter on that detector to beat state-of-the-art for recall, while having a convnet as the post-processing to reach the same accuracy level. This is a actually pretty standard setup for some proprietary face detectors and hopefully, if it is implemented, can bring open-source face detector to the same level

Unfortunately, my current focus is my day work, as well as moving libccv to use CUDNN and have a more flexible deep learning C interface, optimized mobile performance as well.

**Comment by futurely** [comment]
Cheney et al. benchmarked OpenCV and Dlib face detection performance on the IJB-A and FDDB datesets [1].

[1] J. Cheney, B. Klein, A. K. Jain and B. F. Klare, "Unconstrained Face Detection: State of the Art Baseline and Challenges", ICB, Phuket, Thailand, May 19-22, 2015.
