### ISSUE TITLE
DPMcreate: Converting model to OpenCV's XML format

### ISSUE THREAD

**Issue by neumann89** [liuliu/ccv#149]
In the doc you compared your dpmdetect implementation against opencv.

How did you converted the trained model from .m to .xml which is used by opencv's LatentSVMDetector?

**Comment by AfterEight** [comment]
Hi!
I already went through it, so that's my experience: opencv's latentSVM uses voc-release3.x. Afaik, its not working with voc-release >3 as they changed the model output. I think someone wrote an mat2xml.m for version 5, but it was not working for me. 
There is an extra folder from opencv (which is not included in the lib download), you can find here: https://github.com/Itseez/opencv_extra
in folder opencv_extra-master\testdata\cv\latentsvmdetector there is a mat2xml (which is working fine with octave). 
Getting back to your first comment: I'm not sure if liuliu converted the models. The models are integrated in the opencv-extra folder (VOC2007)

**Comment by neumann89** [comment]
Thank you @AfterEight !

**Comment by liuliu** [comment]
Yeah, I did the comparison against voc release model (5 I believe), and use Octave to export its weights. These are a while ago, for later projects in ccv, I did better documentation and scripts for the process, but unfortunately, not for this one.
