### ISSUE TITLE
Model format convertion

### ISSUE THREAD

**Issue by info-edu** [liuliu/ccv#25]
Hi Liuliu,

thanks for the lib it is pretty easy to use for pedestrian detection.
My only problem was the I tried to train the dpm for car detection
and I had a segmentation fault in linear.cpp when train_one
is called by train. I've been trying to find the reason why with
valgrind but unfortunately I had too many errors to be able to 
do anything. The thing is that I already have the models train
for cars and other stuff from the matlab implementation and 
therefore I was wondering if there was no way to have something
to convert this models or directly use them in your code ?
That would be really useful. Anyway thank for the nice work.
Cheers.

**Comment by liuliu** [comment]
Yeah, training one "real" mixture model (such as car), is high on my list (pedestrian is not a real one because it is just one model). You can turn the matlab trained data into ccv format, ccv format is quite straightforward (before the training program implementation, I use the inventor's matlab result as proof-of-correctness for my detection implementation as well).

. /\* start with a dot to indicate it is a done file */
[number of models]

[height of the root classifier] [width of the root classifier]
[4 parameters for bounding box correction, use 0 if no post-bounding box correction]
[root classifier coefficients, width \* height \* 31]
[how many part classifiers]
[part classifier's x, this is the same as the matlab version][y][z, which is 0 for now]
[part classifier's x-coefficient] [y coeeficient] [x^2] [y^2]
[6 parameters for bounding box correction, use 0, the bounding box correction algo in ccv is not compatible with matlab version]
[height of part classifier] [width of part classifier] [counter part number of part classifier, this is not interesting for detection phase, leave it to -1]
[part classifier coefficients, width \* height \* 31]

repeat above for extra models.

The coefficients layout is a bit different from matlab probably, ccv's layout is:
[4 normalization factor][9 contrast insensitive hog][18 contrast sensitive hog]

It is still cumbersome / requires a lot effort, but hope this will help.

**Comment by info-edu** [comment]
Hi Liu Liu,

thanks a lot for the fast answer, I tried converting the model from
matlab, unfortunately I cannot find a way to get the normalization
factor out of the matlab model. Would you have any clue about
how it could be done ? Cheers and thanks again.

On 20 July 2012 21:28, Liu Liu <
reply@reply.github.com

**Comment by liuliu** [comment]
Thyrf, what do you mean by normalization factor? If you mean the bounding box post-estimating factor, matlab model is not compatible to ccv ones, for that part in ccv, you can set it all to 0
