### ISSUE TITLE
collapse in [ndarray exportDataWithCommandBuffer: command_buffer toBuffer: buffer destinationDataType:ccv_nnc_mps_datatype(tensor-›info.datatype) offset:offset rowStrides:rowStrides]; 

### ISSUE THREAD

**Issue by afacelgf** [liuliu/ccv#265]
Hello, running on the iphone14pro 18.1.1 system version, Collapse in [ndarray exportDataWithCommandBuffer: command_buffer toBuffer: buffer destinationDataType:ccv_nnc_mps_datatype(tensor-›info.datatype) offset:offset rowStrides:rowStrides]; , ask for Assist
![Snip20241216_14](https://github.com/user-attachments/assets/416f3bcc-d2fc-4f5b-a90f-6692184c92d2)

**Comment by liuliu** [comment]
Ah, this is typical when MPSGraph has cached the compiled program and then there is a OS upgrade. Usually remove any temp files from the device and then reboot would resolve it.

BTW, this is also why we move more and more of ops off MPSGraph and use Metal directly.

**Comment by afacelgf** [comment]
> Ah, this is typical when MPSGraph has cached the compiled program and then there is a OS upgrade. Usually remove any temp files from the device and then reboot would resolve it.
> 
> BTW, this is also why we move more and more of ops off MPSGraph and use Metal directly.

Thank you, but I don't quite understand what you said about deleting the cache file to solve the problem. We packaged the app, deleted the app, re-installed and re-downloaded the model, or it will crash in this way. Do you mean that this problem can be solved by upgrading the system version of iphone? Is it a bug in ios 18.1.1? The same 18.1.1 version system is normal in iPhone15 pro, please further explain, thank you very much

**Comment by liuliu** [comment]
No worries.

MPSGraph, when you used to build a graph, or call some of its packaged calls, it will implicitly build a Metal program, compile it into some format, and cached on the disk. This format, for some reason, is not compatible from OS version to version, and Apple didn't build any mechanism to clean up these caches during OS update.

That means it might load a program that cause "internal errors" when you have an OS update.

We have logic in Draw Things to partially address this, it looks like this:
```
  static func cleanupTmpDir() {
    let fileManager = FileManager.default
    let tmpDir = NSTemporaryDirectory()
    if let directories = try? fileManager.contentsOfDirectory(atPath: tmpDir) {
      for directory in directories {
        try? fileManager.removeItem(
          atPath: (tmpDir as NSString).appendingPathComponent(directory))
      }
    }
    let urls = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)
    if let documentUrl = urls.first {
      let trashUrl = documentUrl.appendingPathComponent(".Trash")
      if let directories = try? fileManager.contentsOfDirectory(atPath: trashUrl.path) {
        for directory in directories {
          try? fileManager.removeItem(at: trashUrl.appendingPathComponent(directory))
        }
      }
    }
    if let cacheUrl = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first,
      let bundleIdentifier = Bundle.main.bundleIdentifier
    {
      let appUrl = cacheUrl.appendingPathComponent(bundleIdentifier)
      if let directories = try? fileManager.contentsOfDirectory(atPath: appUrl.path) {
        for directory in directories {
          // Remove Metal / GPU related caches that can cause issues across different iOS versions.
          guard directory.contains(".metal") || directory.contains(".gpu") else { continue }
          try? fileManager.removeItem(at: appUrl.appendingPathComponent(directory))
        }
      }
    }
  }
```

You can look into the Temporary directory yourself to verify these file existence.

Even we did that, sometimes it requires a reboot of the said device after delete these files. It doesn't require reinstall the app, but delete the app / reinstall do clean up the temporary directory so that is probably why it fixes for you.

**Comment by afacelgf** [comment]
It was useful and solved the problem, thank you very much
