### ISSUE TITLE
Create a (Google?) group

### ISSUE THREAD

**Issue by haarts** [liuliu/ccv#29]
I'm unsure how to reach you otherwise.

To me it seems that CCV generates a lot of attention. That is not to say that there aren't any questions. I believe a group in which members can help each other out would be beneficial to the project.

**Comment by arorachetan369** [comment]
Sorry, i did not got the meaning...
please b clear with whatever u wanna say>..:)
thank you

**Comment by haarts** [comment]
:) Start a Google Group so people can ask questions. A forum.

**Comment by liuliu** [comment]
Hi, there is nothing stopping others to create a forum for ccv. But for me, there is a lot noises in a forum and hardly can be more helpful. An alternative I can see is to add disqus to ccv's documentation page, much like what PHP does for its documentation page so that the topics can be more concentrated and hopefully noise/signal ratio is lower.
