### ISSUE TITLE
ccv_optical_flow_lucas_kanade design

### ISSUE THREAD

**Issue by inspirit** [liuliu/ccv#34]
hi
looking at current LK implementation it seems we cant provide predefined/precomputed image pyramids to it. so each time u should recreate not only new pyramid but also previous image pyramid. as u may guess its not the best way to handle it...
i would create image pyramid structure to handle that.

**Comment by liuliu** [comment]
Hi, please refer to: http://libccv.org/doc/doc-cache/, ccv relies on this application-wide cache design to mitigate that much cluttered API design.

**Comment by inspirit** [comment]
yes i saw that and i know that u cache results and return it if the one is cached already.
the question is: will it return previous image ready pyramid if input point-set will differ from previous one? i see take into account point sequence signature to generate/identify cache

**Comment by liuliu** [comment]
all ccv calls are cached, so the result of pyramid generation calls (ccv_sample_down), will be cached and later retrieved too. the LK call itself won't be able to retrieve result from cache (the point set is different, as you said). that's why build a new library from ground up is essential for this cache apporach work :-)

**Comment by inspirit** [comment]
ahh right, stupid I am - ccv_sample_down will be cached of course! :)
sorry for missing it
