### ISSUE TITLE
Node module

### ISSUE THREAD

**Issue by yocontra** [liuliu/ccv#36]
Is there any chance you can publish the JS version on NPM?

**Comment by liuliu** [comment]
Sorry, I won't. However, in upcoming ccv 0.4, it will support RESTful API to the mainline ccv functions (such as face detection / pedestrian detection / car detection etc.)

**Comment by yocontra** [comment]
What's the reasoning for not putting it on NPM?

**Comment by liuliu** [comment]
For the javascript one, simply because JS for image processing is out of the question on server-side (in terms of speed / memory consumption etc.). For the C one, because I am working on a RESTful API to make ccv runnable on the server-side as service, thus, a language-specific binding is not worth to put effort into it (any language binding, not just node.js, I am not going to implement Lua binding, Ruby binding, or Python binding for the same reason).
