### ISSUE TITLE
TLD performance

### ISSUE THREAD

**Issue by j0sh** [liuliu/ccv#49]
TLD seems to be 3x slower than reported. According to the docs, it should be taking ~100ms per 320x240 frame on an i7-2620M 2.7GHZ; I'm getting ~300-350 on the same CPU with the webcam as input.

The ferns classifiers seem to be taking a disproportionate amount of time. My guess is cache thrashing, but I haven't investigated deeply yet. Oprofile breakdown: https://gist.github.com/4200732

Here's my code in case I'm doing something wrong:
https://github.com/j0sh/thesis/blob/afc6e1ad37b34dcea5bf1f22524a2c2097fe1b39/ccv.c

**Comment by liuliu** [comment]
I see no where that you asserted the captured frame is 320x240, also you have a small memory leak with x, which won't affect performance, but nevertheless. the OpenCV frame is copied rather than casted (with CCV_IO_NO_COPY), although again, that won't affect performance. My suggestion is to revisit if it is 320x240 indeed. Also, you can use ccv_tld_param_t.rotation to speed it up to near real time.

**Comment by j0sh** [comment]
It is indeed 320x240, see capture code here https://github.com/j0sh/thesis/blob/master/capture.c#L3

Anyway, setting the rotation parameter to 5 seems to have helped, I'm getting ~60ms frames now. Thanks.
