### ISSUE TITLE
tld in javascript?

### ISSUE THREAD

**Issue by bkw** [liuliu/ccv#52]
I was just wondering: Are there any plans of producing a javascript version of the tld algorithm working on typed rgba arrays for using with canvas elements? That would be awesome!

**Comment by liuliu** [comment]
ccv won't. The face detection implementation is doable because the specific operation can be done using native implementation (image resize), TLD's operation will take huge performance hit with any scripting language that doesn't support native vector math (yep, that means all out-of-box scripting languages such as Python, Ruby and Javascript). In ccv 0.4, it has HTTP API support, which supposedly, is language neutral. see more: http://libccv.org/doc/doc-http/

**Comment by bkw** [comment]
I was more thinking about offloading the vector math to webgl shaders. Should be doable.

**Comment by liuliu** [comment]
@bkw that's a huge work for some very diminishing return, ccv won't have that on the roadmap, but if I was drunk and bored one night and want to try out, may give it a shoot.

**Comment by liuliu** [comment]
To clarify why it is harder than the ordinary Javascript version, because you have to devise all these data structures in TLD (or BBF, really) a GPU friendly way, otherwise there is no performance gain.

**Comment by bkw** [comment]
In that case, should you be bored and thirsty any time soon, just give me a holler and I'll supply the booze ;-)

**Comment by bkw** [comment]
To get you in the mood: I found a (german) diploma thesis on implementing sift in OpenGL, both a full gpu based implementation and a hybrid approach with only the pyramids are computed on the gpu and read back

http://www.uni-weimar.de/cms/fileadmin/medien/vr/documents/thesis/DiplomaThesisSebastianHeymann.pdf

The authors claim a speed improvement for bbf even with the hybrid approach. Cheers!

**Comment by bkw** [comment]
The author is on github: @sebastianheymann
