### ISSUE TITLE
ccv_read() raw data with CCV_IO_NO_COPY increases SHA1 compute expense

### ISSUE THREAD

**Issue by mledford** [liuliu/ccv#53]
I noticed that when I run with CCV_IO_NO_COPY things run significantly slower than when I omit the flag. This is strange to me as it seems that all data goes through the ccv_cache_generate_signature() including the SHA1 hash generator. Yet when CCV_IO_NO_COPY is enabled the SHA1 hash takes up significantly more time. I would assume that not copying the data would generally be faster since there isn't a need to allocate and copy the data from one memory location to another but this doesn't seem to be the case. I'm sure I'm missing something but I simply don't see it.

**Comment by liuliu** [comment]
what the scanline size you use? I would suspect that a wrong scanline size used, therefore SHA1 hash computation goes to an excessive memory regions to compute its signature. Yes, it should be faster because NO_COPY avoid the memcpy entirely, but you should be extremely careful with the format you passed into.

**Comment by mledford** [comment]
After investigating this further I believe this to be caused by poor performance when random accesses are performed on the image buffer provided by AVCaptureVideoDataOutput on iOS.
